version: "3"
services:
    db:
      container_name: ${MYSQL_CONTAINER_NAME}
      image: mysql:8.0.13
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${TIMEZONE}
      ports:
        - "${MYSQL_PORTS}:3306"
      volumes:
        - db:/var/lib/mysql
      networks:
        - app-network
    redis:
      container_name: ${REDIS_CONTAINER_NAME}
      image: redis:5.0.3
      ports:
        - "${REDIS_PORTS}:6379"
      volumes:
        - /${APP_PATH}}/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - redis:/data
      networks:
        - app-network
      environment:
        - TZ=${TIMEZONE}
      command: ["/usr/local/bin/redis-server","/usr/local/etc/redis/redis.conf"]
    php:
      container_name: ${PHP_CONTAINER_NAME}
      build:
        context: ./php
        dockerfile: Dockerfile
      depends_on:
        - redis
        - db
      volumes:
        - /${APP_PATH}/www/${APP_CODE_PATH}:/www
        - /${APP_PATH}/supervisor/conf.d:/etc/supervisor/conf.d
        - /${APP_PATH}/supervisor/log:/var/log/supervisor
      networks:
        - app-network
      environment:
        - TZ=${TIMEZONE}
    nginx:
      container_name: ${NGINX_CONTAINER_NAME}
      image: nginx:1.15.7
      ports:
        - "${NGINX_PORTS}:80"
        - "${NGINX_SSL_PORTS}:443"
        - "${NGINX_SUPERVISOR_PORTS}:8080"
      depends_on:
        - php
      volumes:
        - /${APP_PATH}/nginx/conf.d:/etc/nginx/conf.d
        - /${APP_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /${APP_PATH}/nginx/log:/var/log/nginx
        - /${APP_PATH}/www/${APP_CODE_PATH}:/www
      environment:
        - TZ=${TIMEZONE}
      networks:
        - app-network
volumes:
  db:
    driver: local
  redis:
    driver: local
networks:
  app-network:
    driver: bridge